name: 'sync-to-qiniu-action'
description: 'Wait a designated number of milliseconds'
inputs:
  folderPath:
    description: 'The folder which will sync to the qiniu'
    required: true
  fsizeLimit:
    description: 'Maximum upload file size limit(byte)'
    default: 1 * 1024 * 1024 #默认 1M
  mimeLimit:
    description: 'File MimeType'
runs:
  using: 'node12'
  main: 'dist/index.js'
