name: Test
on:
  push:
    branchs:
      - test

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo 123 > ./demo/test.txt
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        git add .
        git commit -m "add test.txt"
        git push
  modify:
    needs: add
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - if: hashFiles('./demo/test.txt')
      run: |
        echo 456 >> ./demo/test.txt
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        git add .
        git commit -m "change test.txt"
        git push
  move:
    needs: modify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - if: hashFiles('./demo/test.txt')
      run: |
        echo ./demo/test.txt ./demo/Test.txt
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        git add .
        git commit -m "move test.txt to Test.txt"
        git push
  delete:
    needs: move
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        rm -f ./demo/Test.txt
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        git add .
        git commit -m "move test.txt to Test.txt"
        git push