name: Test
on:
  push:
    tags: 
      - 'run-test'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
        ref: test
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        git rm 'demo/**'
        git commit -m "delete deme/**"
        git push
  add:
    runs-on: ubuntu-latest
    needs: delete
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
        ref: test
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        mkdir -p demo
        echo 123 > ./demo/test.txt
        git add .
        git commit -m "add test.txt"
        git push
  modify:
    needs: add
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
        ref: test
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - if: hashFiles('./demo/test.txt')
      run: |
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        echo 456 >> ./demo/test.txt
        git add .
        git commit -m "change test.txt"
        git push
  move:
    needs: modify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
        ref: test
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - if: hashFiles('./demo/test.txt')
      run: |
        git config --global user.email "test@qq.com"
        git config --global user.name "laoergege"
        mv ./demo/test.txt ./demo/Test.txt
        git add .
        git commit -m "move test.txt to Test.txt"
        git push