name: Test
on:
  push:
    branchs:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/test
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}