name: Test
on:
  push:
    tags:
      - test

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo 123 >> ./demo/demo.txt
  modify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo 456 >> ./demo/demo.txt
  move:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo ./demo/test.txt ./demo/Demo.txt
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.token }}
    - uses: ./
      with:
        accessKey: ${{ secrets.accessKey }}
        secretKey: ${{ secrets.secretKey }}
        bucket: 'laoergege-blog-images'
        zone: 'Zone_z2'
        path: demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        rm -f ./demo/Demo.txt
